"""Add transaction_min_value and transaction_max_value to Category table

Revision ID: 98603936a4ff
Revises: 6c66972711f9
Create Date: 2026-02-08 19:25:11.164786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98603936a4ff'
down_revision: Union[str, None] = '6c66972711f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('transaction_min_value', sa.Float(), nullable=True))
    op.add_column('categories', sa.Column('transaction_max_value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'transaction_max_value')
    op.drop_column('categories', 'transaction_min_value')
    # ### end Alembic commands ###
